name: Release Plugin

on:
  workflow_run:
    workflows:
      - Functional Tests
    types:
      - completed

permissions:
  contents: write

jobs:
  build-and-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && (github.event.workflow_run.head_branch == '' || github.event.workflow_run.head_branch == null) }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: plugin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: plugin/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build plugin bundle
        run: npm run build

      - name: Determine release tag
        id: tag
        run: |
          git fetch --force --tags origin
          tag_sha="${{ github.event.workflow_run.head_sha }}"
          tag="$(git tag --points-at "${tag_sha}" | head -n 1)"

          if [ -z "$tag" ]; then
            echo "No tag pointing at ${tag_sha}. Skipping release."
            echo "release=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "Release tag: $tag"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "release=true" >> "$GITHUB_OUTPUT"

      - name: Create release
        if: steps.tag.outputs.release == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.tag.outputs.tag }}" \
            --title="${{ steps.tag.outputs.tag }}" \
            --draft \
            main.js ../manifest.json styles.css
